### ISSUE TITLE
Checklist for v0.2.5 release

### ISSUE THREAD

**Issue by nathaneastwood** [nathaneastwood/poorman#65]
- [x] `devtools::spell_check()`
- [x] Run `sh build.sh`
- [x] `revdepcheck::revdep_check()`
- [x] Update `NEWS.md`
- [x] Update `cran-comments.md`
- [x] Bump version number
- [x] `devtools::release()`
- [x] blog
- [x] Update news section in `pkgdown.yml`
- [x] `docker build --no-cache -t nathaneastwood/poorman .`
- [x] `docker push nathaneastwood/poorman`
